// ===== Fuel Types =====
export const fuelTypes = [
    { id: 'petrol', label: 'Petrol', price: 109, unit: '₹/L', emoji: '⛽' },
    { id: 'diesel', label: 'Diesel', price: 97, unit: '₹/L', emoji: '🛢️' },
    { id: 'cng', label: 'CNG', price: 78, unit: '₹/kg', emoji: '💨' },
]

export const quickQuantities = [5, 10, 20, 50]
export const deliveryCharge = 100

// ===== Hyderabad Center (Secunderabad) =====
export const BANGALORE_CENTER = { lat: 17.4399, lng: 78.4983 }

// ===== Mock Fuel Stations (10 Hyderabad locations) =====
export const mockFuelStations = [
    {
        id: 'STN-001',
        name: 'HP Petrol Pump - Gandipet',
        brandName: 'HP',
        location: { lat: 17.3700, lng: 78.3450 },
        address: 'Gandipet Road, Near Osman Sagar',
        city: 'Hyderabad',
        state: 'Telangana',
        pincode: '500075',
        fuelTypes: {
            petrol: { available: true, pricePerLiter: 109.50, stock: 5000 },
            diesel: { available: true, pricePerLiter: 97.80, stock: 5000 },
            cng: { available: false, pricePerLiter: 0, stock: 0 },
        },
        deliveryRadius: 10,
        deliveryCharge: 100,
        isOnline: true,
        rating: 4.6,
        totalDeliveries: 342,
        operatingHours: { open: '06:00', close: '22:00' },
    },
    {
        id: 'STN-002',
        name: 'Indian Oil - Madhapur',
        brandName: 'Indian Oil',
        location: { lat: 17.4486, lng: 78.3908 },
        address: 'Ayyappa Society, Madhapur',
        city: 'Hyderabad',
        state: 'Telangana',
        pincode: '500081',
        fuelTypes: {
            petrol: { available: true, pricePerLiter: 109.10, stock: 4000 },
            diesel: { available: true, pricePerLiter: 96.50, stock: 6000 },
            cng: { available: true, pricePerLiter: 78.50, stock: 3000 },
        },
        deliveryRadius: 8,
        deliveryCharge: 100,
        isOnline: true,
        rating: 4.4,
        totalDeliveries: 518,
        operatingHours: { open: '05:30', close: '23:00' },
    },
    {
        id: 'STN-003',
        name: 'Shell - Gachibowli',
        brandName: 'Shell',
        location: { lat: 17.4401, lng: 78.3489 },
        address: 'Financial District, Gachibowli',
        city: 'Hyderabad',
        state: 'Telangana',
        pincode: '500032',
        fuelTypes: {
            petrol: { available: true, pricePerLiter: 110.20, stock: 3000 },
            diesel: { available: true, pricePerLiter: 98.00, stock: 3000 },
            cng: { available: false, pricePerLiter: 0, stock: 0 },
        },
        deliveryRadius: 12,
        deliveryCharge: 120,
        isOnline: true,
        rating: 4.7,
        totalDeliveries: 201,
        operatingHours: { open: '06:00', close: '22:00' },
    },
    {
        id: 'STN-004',
        name: 'Bharat Petroleum - Kukatpally',
        brandName: 'Bharat Petroleum',
        location: { lat: 17.4947, lng: 78.3996 },
        address: 'KPHB Colony, Kukatpally',
        city: 'Hyderabad',
        state: 'Telangana',
        pincode: '500085',
        fuelTypes: {
            petrol: { available: true, pricePerLiter: 109.00, stock: 5500 },
            diesel: { available: true, pricePerLiter: 97.00, stock: 4500 },
            cng: { available: true, pricePerLiter: 78.00, stock: 2500 },
        },
        deliveryRadius: 10,
        deliveryCharge: 100,
        isOnline: true,
        rating: 4.5,
        totalDeliveries: 430,
        operatingHours: { open: '06:00', close: '22:00' },
    },
    {
        id: 'STN-005',
        name: 'HP - Ameerpet',
        brandName: 'HP',
        location: { lat: 17.4375, lng: 78.4483 },
        address: 'Ameerpet Main Road',
        city: 'Hyderabad',
        state: 'Telangana',
        pincode: '500016',
        fuelTypes: {
            petrol: { available: true, pricePerLiter: 109.50, stock: 6000 },
            diesel: { available: true, pricePerLiter: 97.80, stock: 5000 },
            cng: { available: false, pricePerLiter: 0, stock: 0 },
        },
        deliveryRadius: 8,
        deliveryCharge: 80,
        isOnline: true,
        rating: 4.3,
        totalDeliveries: 280,
        operatingHours: { open: '06:00', close: '21:00' },
    },
    {
        id: 'STN-006',
        name: 'Indian Oil - Secunderabad',
        brandName: 'Indian Oil',
        location: { lat: 17.4399, lng: 78.4983 },
        address: 'MG Road, Secunderabad',
        city: 'Hyderabad',
        state: 'Telangana',
        pincode: '500003',
        fuelTypes: {
            petrol: { available: true, pricePerLiter: 109.10, stock: 4000 },
            diesel: { available: true, pricePerLiter: 96.50, stock: 3500 },
            cng: { available: false, pricePerLiter: 0, stock: 0 },
        },
        deliveryRadius: 7,
        deliveryCharge: 100,
        isOnline: true,
        rating: 4.2,
        totalDeliveries: 612,
        operatingHours: { open: '05:00', close: '23:30' },
    },
    {
        id: 'STN-007',
        name: 'Shell - Hitech City',
        brandName: 'Shell',
        location: { lat: 17.4435, lng: 78.3772 },
        address: 'Cyber Towers Rd, Hitech City',
        city: 'Hyderabad',
        state: 'Telangana',
        pincode: '500081',
        fuelTypes: {
            petrol: { available: true, pricePerLiter: 110.20, stock: 5000 },
            diesel: { available: true, pricePerLiter: 98.00, stock: 4000 },
            cng: { available: true, pricePerLiter: 79.00, stock: 2000 },
        },
        deliveryRadius: 15,
        deliveryCharge: 150,
        isOnline: false,
        rating: 4.8,
        totalDeliveries: 156,
        operatingHours: { open: '06:00', close: '22:00' },
    },
    {
        id: 'STN-008',
        name: 'HP - Kondapur',
        brandName: 'HP',
        location: { lat: 17.4589, lng: 78.3634 },
        address: 'Kondapur Main Road',
        city: 'Hyderabad',
        state: 'Telangana',
        pincode: '500084',
        fuelTypes: {
            petrol: { available: true, pricePerLiter: 109.50, stock: 7000 },
            diesel: { available: true, pricePerLiter: 97.80, stock: 6000 },
            cng: { available: false, pricePerLiter: 0, stock: 0 },
        },
        deliveryRadius: 10,
        deliveryCharge: 100,
        isOnline: true,
        rating: 4.4,
        totalDeliveries: 389,
        operatingHours: { open: '06:00', close: '22:00' },
    },
    {
        id: 'STN-009',
        name: 'Bharat Petroleum - Dilsukhnagar',
        brandName: 'Bharat Petroleum',
        location: { lat: 17.3688, lng: 78.5247 },
        address: 'Dilsukhnagar Main Rd',
        city: 'Hyderabad',
        state: 'Telangana',
        pincode: '500060',
        fuelTypes: {
            petrol: { available: true, pricePerLiter: 109.00, stock: 4500 },
            diesel: { available: true, pricePerLiter: 97.00, stock: 3500 },
            cng: { available: true, pricePerLiter: 78.00, stock: 2000 },
        },
        deliveryRadius: 8,
        deliveryCharge: 90,
        isOnline: true,
        rating: 4.1,
        totalDeliveries: 270,
        operatingHours: { open: '06:00', close: '21:30' },
    },
    {
        id: 'STN-010',
        name: 'Indian Oil - LB Nagar',
        brandName: 'Indian Oil',
        location: { lat: 17.3457, lng: 78.5522 },
        address: 'LB Nagar Ring Road',
        city: 'Hyderabad',
        state: 'Telangana',
        pincode: '500074',
        fuelTypes: {
            petrol: { available: true, pricePerLiter: 109.10, stock: 5000 },
            diesel: { available: true, pricePerLiter: 96.50, stock: 4000 },
            cng: { available: false, pricePerLiter: 0, stock: 0 },
        },
        deliveryRadius: 12,
        deliveryCharge: 100,
        isOnline: true,
        rating: 4.3,
        totalDeliveries: 315,
        operatingHours: { open: '06:00', close: '22:00' },
    },
]

// ===== Mock Delivery Persons =====
export const mockDeliveryPersons = [
    {
        id: 'DEL-001',
        name: 'Rajesh Kumar',
        phoneNumber: '+919876543210',
        vehicleType: 'bike',
        vehicleNumber: 'TS 09 AB 1234',
        stationId: 'STN-001',
        currentLocation: { lat: 17.4180, lng: 78.4370 },
        isAvailable: true,
        isOnline: true,
        rating: 4.8,
        totalDeliveries: 234,
        photoURL: 'https://ui-avatars.com/api/?name=Rajesh+Kumar&background=FF6B35&color=fff&size=128&bold=true',
    },
    {
        id: 'DEL-002',
        name: 'Priya Reddy',
        phoneNumber: '+919876543211',
        vehicleType: 'scooter',
        vehicleNumber: 'TS 09 CD 5678',
        stationId: 'STN-002',
        currentLocation: { lat: 17.4500, lng: 78.3930 },
        isAvailable: true,
        isOnline: true,
        rating: 4.9,
        totalDeliveries: 456,
        photoURL: 'https://ui-avatars.com/api/?name=Priya+Reddy&background=E91E63&color=fff&size=128&bold=true',
    },
    {
        id: 'DEL-003',
        name: 'Suresh Yadav',
        phoneNumber: '+919876543212',
        vehicleType: 'bike',
        vehicleNumber: 'TS 09 EF 9012',
        stationId: 'STN-001',
        currentLocation: { lat: 17.4140, lng: 78.4320 },
        isAvailable: true,
        isOnline: true,
        rating: 4.5,
        totalDeliveries: 189,
        photoURL: 'https://ui-avatars.com/api/?name=Suresh+Yadav&background=4CAF50&color=fff&size=128&bold=true',
    },
    {
        id: 'DEL-004',
        name: 'Amit Verma',
        phoneNumber: '+919876543213',
        vehicleType: 'van',
        vehicleNumber: 'TS 09 GH 3456',
        stationId: 'STN-004',
        currentLocation: { lat: 17.4960, lng: 78.4020 },
        isAvailable: true,
        isOnline: true,
        rating: 4.7,
        totalDeliveries: 312,
        photoURL: 'https://ui-avatars.com/api/?name=Amit+Verma&background=2196F3&color=fff&size=128&bold=true',
    },
    {
        id: 'DEL-005',
        name: 'Kavita Rao',
        phoneNumber: '+919876543214',
        vehicleType: 'scooter',
        vehicleNumber: 'TS 09 IJ 7890',
        stationId: 'STN-003',
        currentLocation: { lat: 17.4420, lng: 78.3500 },
        isAvailable: false,
        isOnline: true,
        rating: 4.6,
        totalDeliveries: 278,
        photoURL: 'https://ui-avatars.com/api/?name=Kavita+Rao&background=9C27B0&color=fff&size=128&bold=true',
    },
]

// ===== Legacy exports (kept for compatibility) =====
export const deliveryPerson = mockDeliveryPersons[0]

export const mockOrders = [
    {
        id: 'ORD-LIVE',
        fuelType: 'Petrol',
        quantity: 15,
        pricePerUnit: 109,
        amount: 1635,
        deliveryCharge: 100,
        totalAmount: 1735,
        total: 1735,
        status: 'on_the_way',
        date: '2025-02-12',
        time: '10:30 PM',
        location: 'Banjara Hills, Hyderabad',
        deliveryAddress: 'Banjara Hills, Hyderabad',
        deliveryPerson: 'Rajesh Kumar',
    },
    {
        id: 'ORD-1006',
        fuelType: 'Diesel',
        quantity: 25,
        pricePerUnit: 97,
        amount: 2425,
        deliveryCharge: 100,
        totalAmount: 2525,
        total: 2525,
        status: 'accepted',
        date: '2025-02-12',
        time: '9:15 PM',
        location: 'Madhapur, Hyderabad',
        deliveryAddress: 'Madhapur, Hyderabad',
        deliveryPerson: 'Suresh Yadav',
    },
    {
        id: 'ORD-1001',
        fuelType: 'Petrol',
        quantity: 20,
        pricePerUnit: 109,
        amount: 2180,
        deliveryCharge: 100,
        totalAmount: 2280,
        total: 2280,
        status: 'delivered',
        date: '2025-02-10',
        time: '2:30 PM',
        location: 'Hitech City, Hyderabad',
        deliveryAddress: 'Hitech City, Hyderabad',
        deliveryPerson: 'Rajesh Kumar',
        rating: 4.8,
    },
    {
        id: 'ORD-1002',
        fuelType: 'Diesel',
        quantity: 10,
        pricePerUnit: 97,
        amount: 970,
        deliveryCharge: 100,
        totalAmount: 1070,
        total: 1070,
        status: 'delivered',
        date: '2025-02-08',
        time: '11:15 AM',
        location: 'Gachibowli, Hyderabad',
        deliveryAddress: 'Gachibowli, Hyderabad',
        deliveryPerson: 'Priya Reddy',
        rating: 4.5,
    },
    {
        id: 'ORD-1003',
        fuelType: 'Petrol',
        quantity: 5,
        pricePerUnit: 109,
        amount: 545,
        deliveryCharge: 100,
        totalAmount: 645,
        total: 645,
        status: 'delivered',
        date: '2025-02-05',
        time: '6:45 PM',
        location: 'Kondapur, Hyderabad',
        deliveryAddress: 'Kondapur, Hyderabad',
        deliveryPerson: 'Amit Verma',
        rating: 4.9,
    },
    {
        id: 'ORD-1004',
        fuelType: 'CNG',
        quantity: 3,
        pricePerUnit: 78,
        amount: 234,
        deliveryCharge: 100,
        totalAmount: 334,
        total: 334,
        status: 'cancelled',
        date: '2025-02-01',
        time: '9:00 AM',
        location: 'Secunderabad, Hyderabad',
        deliveryAddress: 'Secunderabad, Hyderabad',
        deliveryPerson: null,
        rating: null,
    },
    {
        id: 'ORD-1005',
        fuelType: 'Diesel',
        quantity: 50,
        pricePerUnit: 97,
        amount: 4850,
        deliveryCharge: 100,
        totalAmount: 4950,
        total: 4950,
        status: 'delivered',
        date: '2025-01-28',
        time: '4:00 PM',
        location: 'Kukatpally, Hyderabad',
        deliveryAddress: 'Kukatpally, Hyderabad',
        deliveryPerson: 'Suresh Yadav',
        rating: 4.7,
    },
]

export const mockUser = {
    name: 'Krishna Kumar',
    email: 'krishna@email.com',
    phone: '+91 98765 43210',
    photoURL: null,
}
